trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - Extensions/FluidTest.PowerPlatform/*

pool:
  vmImage: 'windows-latest'

extends:
  template: /pipeline-templates/master.yml
  parameters:
      major : 1
      minor: 0
      patch: 0
      revision: 4
      projectPath: 'Extensions/FluidTest.PowerPlatform/FluidTest.PowerPlatform.csproj'
